### PR TITLE
Replaces the blog with reference to Zalando Engineering Blog

### LINKED ISSUE #379: Open source metrics blog posts
- [ ] Blog post on what do we release 
- [ ] Blog post on roadblock - how does it work?
- [ ] Maturity metrics - overview
- [ ] Applying maturity metrics

### PR DESCRIPTION
**Pull request by bocytko**
Issue: Closes #379

## Description

The blog posts have not been updated since 2019. We are replacing the references to the Blog section of this documentation with the [Open Source section of the Zalando Engineering Blog](https://engineering.zalando.com/tags/open-source.html).

## Types of Changes

- Refactoring/improvements

## Tasks

  - [x] Replaced references to blog and its content
  - [x] Replaced non-existing references to `#os-jobs` anchors
  - [x] Migrated posts to Zalando Engineering Blog (internal repository)

## Checklist

N/A

## Screenshots/Videos (OPTIONAL)

N/A

### CODE REVIEW

**Comment by ePaul** [comment]
Unfortunately this has the effect that direct links to these blog post now stop working.
I don't see an easy way of fixing this with Github pages, though (setting up a 404.html with some Javascript to do the redirect might work, but this would then also catch all other missing URLs).

**Comment by ePaul** [comment]
:+1:

**Review by ePaul — APPROVED** [review]
(Please wait until the internal PR is merged, of course.)

**Comment by bocytko** [comment]
> Unfortunately this has the effect that direct links to these blog post now stop working.
> I don't see an easy way of fixing this with Github pages, though (setting up a 404.html with some Javascript to do the redirect might work, but this would then also catch all other missing URLs).

True. There is a plugin for jekyll that apparently allows to build redirect-maps. I decided against trying this out given the low ranking of the affected pages in search engines.

---

The posts have now been migrated – https://engineering.zalando.com/tags/open-source.html
Thus, the PR can be merged. Can you please help with that?

**Review by otrosien — APPROVED** [review]

**Pull request merged**
