### PR TITLE
Add a post about the Postgres operator

### PR DESCRIPTION
**Pull request by sdudoladov**
Add a post about the Postgres operator

### CODE REVIEW

**Comment by baggerspion** [comment]
Thanks for your submission, @zerg-junior! Looks great so far... I just need some preamble from you: author name, date, image to use for header etc. Please take a look at previous blog posts for examples and shout back here if you need any help.

**Comment by sdudoladov** [comment]
@therealpadams  are there any updates on the post ?

**Comment by perploug** [comment]
@therealpadams - I can review and publish this if you are happy with the content

**Comment by perploug** [comment]
@zerg-junior - we are still missing a header image for the post

**Comment by baggerspion** [comment]
I will add an image and publish this tonight.

**Review by baggerspion — APPROVED** [review]
Content is fine. Will merge and add banner separately.

**Pull request merged**
