### PR TITLE
Homepage says "Home" not "Zalando Open Source Team"

### PR DESCRIPTION
**Pull request by perploug**
Explained in title

### CODE REVIEW

**Review by princiya — APPROVED** [review]

**Comment by baggerspion** [comment]
This bug was introduced in one of the docs branches.
Can we return to "Zalando Open Source"?... I think it is important that the site is about the concept and not the team.

**Comment by princiya** [comment]
@therealpadams you mean to change the title to 'Zalando Open Source'?

**Comment by baggerspion** [comment]
It's so unpleasantly hot and sweaty in Split right now, I have no idea **what** I'm talking about.

**Comment by perploug** [comment]
Create you caught that, that was a brain-fart on my part (don't do PRs from a 40 degrees hot conf venue). Yeah the site said "home" and I made a PR to change it to Zalando Open Source Team, but yes it should be Zalando Open Source :)

**Pull request merged**
