### PR TITLE
Projects page

### PR DESCRIPTION
**Pull request by princiya**
Issue: #60 

## Description

As per the discussion [here](https://github.com/zalando/ost/issues/60#issuecomment-385358648), this PR creates `/projects/index.html` to serve Zalando's all open source projects from scratch.

## Types of Changes

_What types of changes does your code introduce? remove the points which aren't applicable:_

- New feature (non-breaking change which adds functionality)

## Tasks

- [x] List all projects
- [x] Add maximum limit for pagination (logic to disable the `Load More Results` button)
- [x] Display statistics for individual projects
- [x] Filter by programming languages
- [x] Filter by Zalando Github Organisations
- [x] `Load More Results` button for paginated results
- [x] Dress-Code styles
- [x] Add SVG icons for all programming languages
- [x] Spinner icon to show loading state
- [x] Add Google Analytics: Issue #55 
- ~~Cache the results to avoid additional calls to the Github API via Catwatch~~
- ~~Group the cached results based on programming languages~~
- ~~Group the cached results based on Zalando Github Organisations~~
 
## Screenshots/Videos (OPTIONAL)

image

### CODE REVIEW

**Review by baggerspion — COMMENTED** [review]
Why is the loadMoreProjects.js not in "assets"?

**Comment by princiya** [comment]
@therealpadams I have moved all files related to dynamic code into `components` directory.

**Comment by princiya** [comment]
The website projects page is ready to replace the existing page for https://zalando.github.io/. 
[Here](https://github.com/zalando/ost/issues/60#issuecomment-385358648) is the discussion about the existing setup for `zalando.github.io`. 

Below are the next steps before we deploy this PR:

- Archive the existing `zalando.github.io` repo - https://github.com/zalando/zalando.github.io
- This PR is a replacement to - https://github.com/zalando-incubator/zalando.github.io-dev. So `zalando.github.io-dev` is good to be archived too. 
  - Any further extensions to the Open Source team website, projects pages can be continued `HERE`.
  - _The detailed scope for future work to be drafted. Add Wiki page_ (**todo**) #82 
- The [gulp](https://github.com/zalando-incubator/zalando.github.io-dev/blob/master/gulpfile.js#L177) script from the [zalando.github.io-dev](https://github.com/zalando-incubator/zalando.github.io-dev#-how-to-deploy), builds the artifact and pushes new code commits into `zalando.github.io`.
   - To prevent unwanted code commits coming, update `Collaborators & Teams` - https://github.com/zalando/zalando.github.io/settings/collaboration.
   - Members only get `READ` permissions.
   - This way, we can ensure nobody else is able to push changes into `THIS` updated repo.
   - All new pull requests will have to be opened `HERE` and the Open Source team can review, approve and merge.
- Lastly, rename `THIS` repo to `zalando.github.io`.
   - Make it public.
   - Point it to `opensource.zalando.net`

**Note** _`THIS`, `HERE` refer to this repo - https://github.com/zalando/ost_

**Review by baggerspion — APPROVED** [review]
Let's reach out to the Guild before we finally deploy this to zalando.github.io

**Pull request merged**
